server:
  servlet:
    context-path: /ums
  session-timeout: 172800 # 48Сʱ
  #    tomcat:
  #        max-threads: 1000
  #        min-spare-threads: 30
  #port: 8443


  tomcat:
    max-swallow-size: -1
  port: 8078


#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: 123456
#    keyStoreType: PKCS12
#    keyAlias: tomcat
#    enabled: true


spring:
  application:
    name: ums-admin
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null

  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  devtools:
    restart:
      enabled: true
      additional-paths: src


jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: ums-admin-secret #JWT加解密使用的密钥
  expiration: 2592000  #JWT的超期限时间(60*60*24 (86400) 一天)
  tokenHead: Bearer  #JWT负载中拿到开头

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui/*
      - /swagger-resources/**
      - /v2/api-docs
      - /v3/api-docs
      - /webjars/**
      - /**/doc.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /**/*.icon
      - /**/*.ttf
      - /**/*.woff
      - /actuator/**
      - /druid/**
      - /admin/login
      - /common/sms
      - /validateCode/**
      - /uploadFiles/**


uploadFile:
  resourceHandler: /uploadFiles/**   #文件虚拟路径映射
  location: C:/data/ #自定义上传文件本地保存路径


defaultpassword: 123



# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0整合
  try-host: http://localhost:${server.port}

#mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    ## 关闭sql打印
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

  global-config:
    # 逻辑删除配置
    db-config:
      #更新字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0

#mybatis:
#  mapper-locations:
#    - classpath:dao/*.xml
#    - classpath*:mapper/*.xml
logging:
  config: classpath:logback-spring.xml

wechat:
  appid: wx02253cc6c534f17c
  secret: b6297950ea303f00654aae375c6cfedf
  login:
    url: https://api.weixin.qq.com/sns/jscode2session
  ##微信一键首次登陆插入用户表的初始密码
  initpwd: 123
  ##微信一键首次登陆插入用户表的初始昵称
  initnickname: lQj