server:
  session-timeout: 172800 # 48Сʱ
  #    tomcat:
  #        max-threads: 1000
  #        min-spare-threads: 30
  port: 8099

spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb
  devtools:
    restart:
      enabled: true
  cache:
    type: ehcache
    ehcache:
      config: config/ehcache.xml

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 3600 #JWT的超期限时间(60*60)
  tokenHead: Bearer  #JWT负载中拿到开头

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload

uploadFile:
  resourceHandler: /uploadFiles/**   #文件虚拟路径映射
  location: D:/data/ #自定义上传文件本地保存路径

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:mapper/*.xml