dispatch:
  uploadPath: D:/var/uploaded_files/
logging:
  level:
    root: info
    com.bootdo: info
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.251.90:3306/bankserver?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: lk9527

#    url: jdbc:mysql://127.0.0.1:3306/chef?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: root
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 1
    timeout: 3000
    maxIdle: 50
    maxTotal: 200
    maxWaitMillis: 2000
    testOnBorrow: true

pic:
  suffix: jpg,png,gif,mp4

##解密
rsa:
  privateKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAIaTvIKU1yFzDk2iAxh8QUIjGEZEjxEcGXCfVoZOAdkMw1dYWb7W5lupiD8/1sfOh2XCQfMxr7lhub9/weU59A9UPznVXhEIXSezQ763Mk0H97ZtET2/b1v5yBiDVYb8ZkMDAi1ds4a1VexsF/w1RBRZlenxThal6dMr+Xb0KD+dAgMBAAECgYAJ9QpgmwSj2/B1/APAnwjxDMmyAUaYnHyhYZi0TTdDyPb3EnlpblsS8yM6ks2gcP6Bn/LjPIzk6X8l1R0Sicwt7nf9ITjHAbJmqpqpxq84pu3Pjehwypv+2Cg6qUVAv6tdoaYG3Xuc0hXvrgpDXrdUev04A6INFeo4WnCe3sEAfQJBANPNIqR+vt+LKvH6uCUc3qdAWwJDhhRzr2hbo+6YwivimQZp+s2mNcGnuh+tQ5Hbsdy1RBZJBvWfBSLsicsopb8CQQCiqR+gfA4wIxz1lkvskszRq/sVENXCEMSU2fXmoEJCEao/+mu2TX+ITztT3ShntpAV1rjsEaQl9GtGZiHvTQmjAkEAyB/4L72i1M5GkcX44PhaWWYxl/39Xq3Ae7a7OuMT9Stys+DHnjECciztbKjmQ5d2g7iy0OvHq6XJ0Kn3uQJ7OQJAUggOviWyFg6vPR9l/NHv31HnVzFdS/ie2x6sx3lM0PsNrCRDi/W7emfS2LFw/hTwx0K5kbw31zhTnXZGaOOmFwJASaqHp4gLi4gOmwNuiobdod0rxWEcFJ/nyMDestAC1StAIMm/HAMepsLChHqfcUw7OfkltgJfQsdVzX6Q7ag6pQ==
